### PR TITLE
Add euler to quat

### PR DESCRIPTION
**Pull request by kd0aij**
needed for hil_state_quaternion message (Euler angles would have been sufficient, but the hil_state message is deprecated)

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by kd0aij** [comment]
@bkueng I construct a quaternion from Euler angles using code copied from lib/ecl/matrix/matrix/Quatern.cpp:Quaternion(const Euler &).
https://github.com/kd0aij/jMAVSim/blob/3fbb791aa32475b6c5628a8e7055218713c34d5a/src/me/drton/jmavsim/MAVLinkHILSystem.java#L188
Is it possible that code is wrong? I'll see if I can find any unit test code which validates it.

**Comment by bkueng** [comment]
I've seen it, this looks correct. I tested in jMAVSim: if you press `r`, you see the raw numbers of the attitude. If the pitch angle of the vehicle changes, the first value of the attitude changes, and the last for yaw. So it seems that in jMAVSim, roll and pitch are swapped.

**Comment by kd0aij** [comment]
@bkueng There is unit test code for Quaternion.hpp, but I can't see how or when it is run. Can you point me in the right direction for understanding that?
And I'm guessing that the problem must be ENU vs NED, which is swapping the x and y axes.

**Comment by bkueng** [comment]
Commands to run the unit tests should be these: https://github.com/PX4/Matrix/blob/master/.travis.yml#L9
yes looks like ENU, but then the z-axis should be inverted too.

**Comment by kd0aij** [comment]
Thanks and Yes, it is confusing that the sign of yaw doesn't need to be flipped.

**Pull request merged**
